# Generated by Django 3.0.2 on 2020-02-04 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200202_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dep',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=1000)),
                ('createdtime', models.TimeField(max_length=32)),
                ('file', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.user')),
            ],
        ),
    ]
